[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
  "cd server/CcnaBlog.Api",
  "dotnet restore",
  "dotnet publish -c Release -o out"
]

[start]
cmd = "cd server/CcnaBlog.Api/out && dotnet CcnaBlog.Api.dll"
