[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
  "dotnet restore server/CcnaBlog.Api/CcnaBlog.Api.csproj",
  "dotnet publish server/CcnaBlog.Api/CcnaBlog.Api.csproj -c Release -o out"
]

[start]
cmd = "dotnet out/CcnaBlog.Api.dll"
